"use client";
import { useEffect, useState } from "react";
import type { ChangeEvent } from "react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { api } from "@/lib/api";

type Settings = {
  minimum_residual_m3:number; minimum_residual_ratio:number; persistence_intervals:number;
  minimum_coverage:number; freshness_limit_seconds:number; alignment_tolerance_seconds:number;
  verification_required_intervals:number; quiet_hours_start:string; quiet_hours_end:string; site_timezone:string;
};
type NodeConfig={id:string;label:string;kind:string;expected_interval_minutes:number;known_unmetered_m3_per_interval:number;buffered:boolean;storage_capacity_m3:number|null;storage_change_m3_per_interval:number|null;active:boolean};

export default function SettingsPage(){
  const [form,setForm]=useState<Settings|null>(null); const [nodes,setNodes]=useState<NodeConfig[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const load=async()=>{try{const [s,t]=await Promise.all([api<Settings>('/sites/northbridge/settings'),api<{nodes:NodeConfig[]}>('/sites/northbridge/topology')]);setForm(s);setNodes(t.nodes);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}};
  useEffect(()=>{load()},[]);
  const update=(key:keyof Settings,value:string)=>{if(!form)return; const numeric = !['quiet_hours_start','quiet_hours_end','site_timezone'].includes(key); setForm({...form,[key]:numeric?Number(value):value} as Settings)};
  const save=async()=>{if(!form)return;setSaving(true);setError("");setMessage("");try{const saved=await api<Settings>('/sites/northbridge/settings',{method:'PUT',body:JSON.stringify(form)});setForm(saved);setMessage('Reconciliation settings saved. New intervals use these deterministic rules.')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setSaving(false)}};
  const patchNode=(id:string,changes:Partial<NodeConfig>)=>setNodes(rows=>rows.map(n=>n.id===id?{...n,...changes}:n));
  const saveNode=async(node:NodeConfig)=>{setSaving(true);setError('');setMessage('');try{const saved=await api<NodeConfig>(`/sites/northbridge/topology/${node.id}`,{method:'PUT',body:JSON.stringify({expected_interval_minutes:node.expected_interval_minutes,known_unmetered_m3_per_interval:node.known_unmetered_m3_per_interval,buffered:node.buffered,storage_capacity_m3:node.storage_capacity_m3,storage_change_m3_per_interval:node.storage_change_m3_per_interval,active:node.active})});patchNode(node.id,saved);setMessage(`${node.label} accounting configuration saved.`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setSaving(false)}};
  const configurable=nodes.filter(n=>n.kind==='UNMETERED'||n.buffered||n.storage_capacity_m3!==null);
  return <AppShell><div className="page"><PageHeader title="Reconciliation settings" description="Explicit operational policy: thresholds, evidence gates, known-unmetered allowances and storage behavior. Nothing here is learned by a model." actions={<button className="btn btn-primary" disabled={!form||saving} onClick={save}>{saving?'Saving…':'Save rules'}</button>}/>
    {error&&<div className="card error-banner">{error}</div>}{message&&<div className="card success-banner">{message}</div>}
    {!form?<div className="muted">Loading settings…</div>:<div className="grid-2">
      <Section title="Anomaly rules"><NumberField label="Minimum residual (m³)" value={form.minimum_residual_m3} step="0.01" onChange={v=>update('minimum_residual_m3',v)}/><NumberField label="Minimum residual ratio" value={form.minimum_residual_ratio} step="0.01" onChange={v=>update('minimum_residual_ratio',v)}/><NumberField label="Persistence intervals" value={form.persistence_intervals} step="1" onChange={v=>update('persistence_intervals',v)}/></Section>
      <Section title="Evidence gates"><NumberField label="Minimum downstream coverage" value={form.minimum_coverage} step="0.01" onChange={v=>update('minimum_coverage',v)}/><NumberField label="Freshness limit (seconds)" value={form.freshness_limit_seconds} step="30" onChange={v=>update('freshness_limit_seconds',v)}/><NumberField label="Timestamp tolerance (seconds)" value={form.alignment_tolerance_seconds} step="10" onChange={v=>update('alignment_tolerance_seconds',v)}/></Section>
      <Section title="Repair verification"><NumberField label="Healthy intervals required" value={form.verification_required_intervals} step="1" onChange={v=>update('verification_required_intervals',v)}/><TextField label="Quiet hours start" type="time" value={form.quiet_hours_start} onChange={v=>update('quiet_hours_start',v)}/><TextField label="Quiet hours end" type="time" value={form.quiet_hours_end} onChange={v=>update('quiet_hours_end',v)}/></Section>
      <Section title="Site"><TextField label="Timezone" value={form.site_timezone} onChange={v=>update('site_timezone',v)}/><Static label="Authentication" value="Disabled — demo identities only"/><Static label="AI / ML" value="None"/><Static label="Physical hardware" value="Not required for MVP"/></Section>
    </div>}
    <div className="card" style={{padding:20,marginTop:16}}><div className="kicker">Topology accounting</div><h2 style={{fontSize:22,margin:'7px 0 5px'}}>Known-unmetered and buffered boundaries</h2><p className="muted" style={{fontSize:13,lineHeight:1.6,maxWidth:860}}>These values are first-class evidence inputs. LeakLedger subtracts configured legitimate unmetered use and reduces certainty around storage rather than misclassifying either as leakage.</p>{configurable.length===0?<div className="empty-state">No special topology nodes configured.</div>:<div style={{display:'grid',gap:12,marginTop:16}}>{configurable.map(n=><div className="card2" key={n.id} style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',marginBottom:12}}><div><strong>{n.label}</strong><div className="muted" style={{fontSize:11,marginTop:3}}>{n.id} · {n.kind}</div></div><button className="btn" disabled={saving} onClick={()=>saveNode(n)}>Save node</button></div><div className="topology-config-grid"><NumberField label="Expected interval (min)" value={n.expected_interval_minutes} step="1" onChange={v=>patchNode(n.id,{expected_interval_minutes:Number(v)})}/><NumberField label="Known unmetered (m³/interval)" value={n.known_unmetered_m3_per_interval} step="0.01" onChange={v=>patchNode(n.id,{known_unmetered_m3_per_interval:Number(v)})}/><NumberField label="Storage capacity (m³)" value={n.storage_capacity_m3??0} step="0.1" onChange={v=>patchNode(n.id,{storage_capacity_m3:Number(v)||null})}/><NumberField label="Storage Δ (m³/interval)" value={n.storage_change_m3_per_interval??0} step="0.01" onChange={v=>patchNode(n.id,{storage_change_m3_per_interval:Number(v)||null})}/><label style={{display:'flex',gap:8,alignItems:'center',fontSize:13}}><input type="checkbox" checked={n.buffered} onChange={(e:ChangeEvent<HTMLInputElement>)=>patchNode(n.id,{buffered:e.target.checked})}/>Buffered/storage boundary</label><label style={{display:'flex',gap:8,alignItems:'center',fontSize:13}}><input type="checkbox" checked={n.active} onChange={(e:ChangeEvent<HTMLInputElement>)=>patchNode(n.id,{active:e.target.checked})}/>Active</label></div></div>)}</div>}</div>
    <div className="card" style={{padding:18,marginTop:16}}><div className="kicker">Why these are not confidence scores</div><p className="muted" style={{lineHeight:1.65,marginBottom:0}}>LeakLedger exposes coverage, completeness, freshness, alignment and storage assumptions separately. A conclusion either satisfies the configured evidence gates or it does not.</p></div>
  </div></AppShell>
}
function Section({title,children}:{title:string,children:React.ReactNode}){return <div className="card" style={{padding:20}}><h2 style={{fontSize:20,margin:'0 0 16px'}}>{title}</h2><div style={{display:'grid',gap:12}}>{children}</div></div>}
function NumberField({label,value,step,onChange}:{label:string,value:number,step:string,onChange:(v:string)=>void}){return <label><span className="field-label">{label}</span><input className="input" type="number" step={step} value={Number.isFinite(value)?value:0} onChange={(e:ChangeEvent<HTMLInputElement>)=>onChange(e.target.value)}/></label>}
function TextField({label,value,type='text',onChange}:{label:string,value:string,type?:string,onChange:(v:string)=>void}){return <label><span className="field-label">{label}</span><input className="input" type={type} value={value} onChange={(e:ChangeEvent<HTMLInputElement>)=>onChange(e.target.value)}/></label>}
function Static({label,value}:{label:string,value:string}){return <div style={{display:'flex',justifyContent:'space-between',gap:16,padding:'11px 0',borderTop:'1px solid var(--line)',fontSize:13}}><span className="muted">{label}</span><strong>{value}</strong></div>}
