"use client";
import { useEffect,useMemo,useState } from "react";
import { ChevronRight, CircleDot } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { Status } from "@/components/Status";
import { api,fmt } from "@/lib/api";

export default function Topology(){const [data,setData]=useState<any>(null);const [selected,setSelected]=useState<any>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const load=()=>api<any>('/sites/northbridge/topology').then(d=>{setData(d);setError("");if(selected){setSelected(d.nodes.find((n:any)=>n.id===selected.id)||null)}}).catch(e=>setError(e instanceof Error?e.message:String(e))).finally(()=>setLoading(false));useEffect(()=>{load();const t=setInterval(load,2500);return()=>clearInterval(t)},[]);const byId=useMemo(()=>Object.fromEntries((data?.nodes||[]).map((n:any)=>[n.id,n])),[data]);return <AppShell><div className="page"><PageHeader title="Meter topology" description="LeakLedger descends only through trustworthy anomalous branches. It stops where coverage, timing or data quality no longer supports a narrower claim."/>{error&&<div className="card error-banner">{error}</div>}<div className="topology-layout" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(300px,380px)',gap:16}}><div className="card" style={{padding:22,minHeight:580}}><div className="kicker">Directed water accounting graph</div><div style={{marginTop:22}}>{loading?<div className="empty-state">Loading topology…</div>:!data?.tree?.length?<div className="empty-state">No topology configured.</div>:data?.tree?.map((n:any)=><TreeNode key={n.id} node={n} byId={byId} depth={0} select={setSelected}/>)}</div></div><div className="card" style={{padding:20,position:'sticky',top:20,height:'fit-content'}}>{selected?<><div className="kicker">Node evidence</div><h2 style={{fontSize:24,margin:'8px 0 4px'}}>{selected.label}</h2><div className="muted" style={{fontSize:12}}>{selected.id}</div><div style={{marginTop:14}}><Status value={selected.state}/></div>{selected.balance?<div style={{display:'grid',gap:11,marginTop:20,fontSize:13}}><KV k="Inflow" v={`${fmt(selected.balance.inflow_m3)} m³`}/><KV k="Measured children" v={`${fmt(selected.balance.measured_children_m3)} m³`}/><KV k="Known unmetered" v={`${fmt(selected.balance.known_unmetered_m3)} m³`}/><KV k="Unexplained" v={`${fmt(selected.balance.residual_m3)} m³`}/><KV k="Coverage" v={`${Math.round(selected.balance.coverage*100)}%`}/><KV k="Completeness" v={`${Math.round(selected.balance.completeness*100)}%`}/><KV k="Evidence" v={selected.balance.evidence_quality}/><div className="card2" style={{padding:12,lineHeight:1.6}}>{selected.balance.explanation}</div></div>:<p className="muted">No reconciliation has been calculated for this node yet.</p>}</>:<p className="muted">Select a node to inspect the arithmetic and evidence gates behind its current state.</p>}</div></div></div></AppShell>}
function TreeNode({node,byId,depth,select}:{node:any,byId:any,depth:number,select:(n:any)=>void}){const d=byId[node.id];return <div style={{marginLeft:depth?28:0,position:'relative'}}>{depth>0&&<div style={{position:'absolute',left:-18,top:0,bottom:20,borderLeft:'1px solid var(--line)'}}/>}<button onClick={()=>select(d)} style={{width:'100%',display:'grid',gridTemplateColumns:'24px minmax(180px,1fr) 120px 120px 140px',gap:10,alignItems:'center',padding:'10px 12px',marginBottom:6,border:'1px solid var(--line)',borderRadius:9,background:'#0b1512',color:'inherit',textAlign:'left'}}><CircleDot size={16} color={d?.state==='ANOMALOUS'?'var(--danger)':d?.state?.includes('INSUFFICIENT')?'var(--warn)':'var(--accent)'}/><div><strong>{node.label}</strong><div className="muted" style={{fontSize:11}}>{node.id}</div></div><span>{d?.balance?`${fmt(d.balance.residual_m3)} m³`:'—'}</span><span className="muted">{d?.balance?`${Math.round(d.balance.coverage*100)}% covered`:'—'}</span><Status value={d?.state||node.kind}/></button>{node.children?.map((c:any)=><TreeNode key={c.id} node={c} byId={byId} depth={depth+1} select={select}/>)}</div>}
function KV({k,v}:{k:string,v:string}){return <div style={{display:'flex',justifyContent:'space-between',gap:20,borderBottom:'1px solid var(--line)',paddingBottom:8}}><span className="muted">{k}</span><strong>{v}</strong></div>}
