import Link from "next/link";
import { ArrowRight, CheckCircle2, Database, GitBranch, ShieldCheck, Wrench } from "lucide-react";
import { Logo } from "@/components/Logo";

const Row = ({left,right,accent=false}:{left:string,right:string,accent?:boolean}) => <div style={{display:"flex",justifyContent:"space-between",gap:24,padding:"10px 0",borderBottom:"1px solid var(--line)",fontVariantNumeric:"tabular-nums"}}><span className="muted">{left}</span><strong style={{color:accent?"var(--danger)":"var(--text)"}}>{right}</strong></div>;

export default function Landing(){
  return <main>
    <header style={{position:"sticky",top:0,zIndex:20,background:"rgba(7,17,15,.92)",backdropFilter:"blur(10px)",borderBottom:"1px solid var(--line)"}}>
      <div style={{maxWidth:1180,margin:"0 auto",padding:"14px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:24}}>
        <Logo/><nav className="landing-nav" style={{display:"flex",alignItems:"center",gap:24,fontSize:14,color:"var(--muted)"}}><a href="#how">How it works</a><a href="#architecture">Architecture</a><a href="#why">Why LeakLedger</a><Link href="/signin" className="btn">Sign in</Link><Link href="/signin" className="btn btn-primary">Open Demo</Link></nav>
      </div>
    </header>

    <section className="landing-hero" style={{maxWidth:1180,margin:"0 auto",padding:"92px 24px 72px",display:"grid",gridTemplateColumns:"1.05fr .95fr",gap:64,alignItems:"center"}}>
      <div><div className="kicker">Water reconciliation control plane</div><h1 style={{fontSize:70,lineHeight:.98,letterSpacing:"-.065em",margin:"18px 0 24px",maxWidth:700}}>Account for every litre.</h1><p style={{fontSize:20,lineHeight:1.65,color:"var(--muted)",maxWidth:680}}>LeakLedger reconciles existing water meters, isolates unexplained losses to the deepest trustworthy boundary, and refuses to close incidents until new readings prove the repair worked.</p><div style={{display:"flex",gap:10,marginTop:30}}><Link className="btn btn-primary" href="/signin">Open Live Demo <ArrowRight size={16} style={{display:"inline",marginLeft:5}}/></Link><a className="btn" href="#how">See how it works</a></div><div style={{display:"flex",gap:22,marginTop:26,color:"var(--muted)",fontSize:13}}><span>NO AI</span><span>NO CAMERAS</span><span>NO SPECIAL HARDWARE FOR DEMO</span></div></div>
      <div className="card" style={{padding:22,boxShadow:"0 30px 80px rgba(0,0,0,.28)"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:18}}><div><div className="kicker">Campus water ledger</div><strong style={{fontSize:18}}>10:00–10:15</strong></div><span className="status status-ANOMALOUS">ANOMALOUS</span></div><Row left="Entered at Campus Main" right="20.62 m³"/><Row left="Accounted downstream" right="18.18 m³"/><Row left="Known unmetered" right="0.40 m³"/><Row left="Unexplained" right="2.04 m³" accent/><div style={{marginTop:18,padding:14,border:"1px solid #4e332d",background:"#1d1210",borderRadius:9}}><div style={{fontSize:12,color:"#f0a79f",fontWeight:800,letterSpacing:'.08em'}}>DEEPEST TRUSTWORTHY ANOMALY</div><div style={{fontSize:20,fontWeight:850,marginTop:5}}>Hostel B Main</div><div className="muted" style={{fontSize:13,marginTop:5}}>Localisation stops before the common branch because part of downstream consumption is explicitly unmetered.</div></div></div>
    </section>

    <section id="how" style={{borderTop:"1px solid var(--line)",borderBottom:"1px solid var(--line)",background:"#091310"}}><div style={{maxWidth:1180,margin:"0 auto",padding:"72px 24px"}}><div className="kicker">Not another consumption dashboard</div><h2 style={{fontSize:42,letterSpacing:"-.045em",margin:"12px 0 12px"}}>Water monitoring tells you what changed. LeakLedger reconciles what cannot be explained.</h2><div className="landing-two" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginTop:32}}><div className="card" style={{padding:24}}><div className="muted" style={{fontSize:13}}>Traditional monitoring</div><div style={{fontSize:28,fontWeight:850,marginTop:10}}>“Usage increased 18%.”</div><p className="muted">Useful context, but it does not prove where the missing water is or whether a repair succeeded.</p></div><div className="card" style={{padding:24,borderColor:"#315448"}}><div style={{fontSize:13,color:"var(--accent)"}}>LeakLedger</div><div style={{fontSize:28,fontWeight:850,marginTop:10}}>“0.35 m³ remains unexplained inside Hostel B.”</div><p className="muted">The conclusion carries its own arithmetic, coverage, completeness and localisation boundary.</p></div></div></div></section>

    <section style={{maxWidth:1180,margin:"0 auto",padding:"72px 24px"}}><div className="kicker">Operational lifecycle</div><div className="landing-five" style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:10,marginTop:20}}>{[[Database,"Reconcile"],[ShieldCheck,"Validate"],[GitBranch,"Localise"],[Wrench,"Repair"],[CheckCircle2,"Verify"]].map(([Icon,label],i)=>{const I=Icon as typeof Database; return <div className="card" key={String(label)} style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between"}}><I size={20}/><span className="muted" style={{fontSize:12}}>0{i+1}</span></div><strong style={{display:"block",marginTop:26,fontSize:18}}>{String(label)}</strong></div>})}</div></section>

    <section id="why" style={{maxWidth:1180,margin:"0 auto",padding:"32px 24px 72px"}}><div className="card landing-fail" style={{padding:32,display:"grid",gridTemplateColumns:".8fr 1.2fr",gap:48,alignItems:"center"}}><div><div className="kicker">Fail closed by design</div><h2 style={{fontSize:38,letterSpacing:"-.04em",margin:"12px 0"}}>Missing evidence stops the accusation.</h2><p className="muted" style={{lineHeight:1.7}}>If a downstream meter disappears, clock alignment fails, a counter resets, or coverage is too low, LeakLedger pauses leak classification instead of turning incomplete observability into a confident alert.</p></div><div className="card2" style={{padding:20}}><Row left="Hostel B Floor 2" right="NO READING — 37 MIN"/><Row left="Downstream completeness" right="67%"/><Row left="Evidence" right="INSUFFICIENT"/><div style={{paddingTop:16,color:"var(--warn)",fontWeight:800}}>Leak classification paused until trustworthy evidence returns.</div></div></div></section>

    <section id="architecture" style={{borderTop:"1px solid var(--line)",background:"#091310"}}><div style={{maxWidth:1180,margin:"0 auto",padding:"72px 24px"}}><div className="kicker">AWS-native event flow</div><h2 style={{fontSize:42,letterSpacing:"-.045em",margin:"12px 0 28px"}}>Every reading becomes evidence, not just a chart point.</h2><div className="landing-architecture" style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:8,alignItems:"center"}}>{["API Gateway","Lambda","S3 Raw Archive","EventBridge","SQS","Reconciliation","DynamoDB"].map((x,i)=><div key={x} style={{display:"contents"}}><div className="card" style={{padding:"18px 10px",textAlign:"center",fontSize:13,fontWeight:750}}>{x}</div>{i<6&&<ArrowRight size={15} className="muted"/>}</div>)}</div><p className="muted" style={{marginTop:22}}>Structured CloudWatch logs and metrics make duplicates, reconciliation decisions, incidents and repair verification inspectable end to end.</p></div></section>

    <footer className="landing-footer" style={{maxWidth:1180,margin:"0 auto",padding:"26px 24px 44px",display:"flex",justifyContent:"space-between",color:"var(--muted)",fontSize:13}}><Logo/><span>Deterministic demo • fictional campus data • no AI</span></footer>
  </main>
}
