"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Droplets, Gauge, ShieldCheck, Waves } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { Status } from "@/components/Status";
import { api, fmt } from "@/lib/api";

export default function Overview(){
  const [data,setData]=useState<any>(null); const [err,setErr]=useState('');
  const load=()=>api<any>('/sites/northbridge/overview').then(setData).catch(e=>setErr(e.message));
  useEffect(()=>{load(); const t=setInterval(load,2500); return()=>clearInterval(t)},[]);
  const b=data?.current_balance;
  return <AppShell><div className="page"><PageHeader title="Water accountability" description="A live reconciliation of what entered the campus, what is accounted for downstream, and what remains unexplained." actions={<Link className="btn btn-primary" href="/replay">Open Replay Lab</Link>}/>{err&&<div className="card" style={{padding:16,color:'var(--danger)'}}>Backend unavailable: {err}</div>}{!data?<div className="muted">Loading live site state…</div>:<>
    <div className="card" style={{padding:22,marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:20}}><div><div className="kicker">Current water balance</div><div style={{display:'flex',alignItems:'baseline',gap:10,marginTop:9}}><strong className="big-number" style={{fontSize:44}}>{fmt(b?.inflow_m3)} m³</strong><span className="muted">entered this interval</span></div></div><Status value={b?.state}/></div><div className="grid-4" style={{marginTop:22}}><Metric icon={Droplets} label="Measured downstream" value={`${fmt(b?.measured_children_m3)} m³`}/><Metric icon={Waves} label="Known unmetered" value={`${fmt(b?.known_unmetered_m3)} m³`}/><Metric icon={AlertTriangle} label="Unexplained" value={`${fmt(b?.residual_m3)} m³`} danger={b?.residual_m3>0.05}/><Metric icon={ShieldCheck} label="Evidence" value={b?.evidence_quality||'—'}/></div>{b&&<div className="card2" style={{padding:14,marginTop:16,fontSize:13,lineHeight:1.6}}>{b.explanation}</div>}</div>
    <div className="grid-2"><div className="card" style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div className="kicker">Active incident</div><h2 style={{margin:'7px 0 0',fontSize:22}}>{data.active_incident?data.active_incident.id:'No active incident'}</h2></div>{data.active_incident&&<Status value={data.active_incident.status}/>}</div>{data.active_incident?<><div style={{marginTop:18,fontSize:28,fontWeight:850}}>{data.active_incident.deepest_trustworthy_node_id}</div><p className="muted" style={{lineHeight:1.6}}>{data.active_incident.boundary_explanation}</p><Link href="/incidents" style={{display:'inline-flex',alignItems:'center',gap:6,fontWeight:800,fontSize:13,color:'var(--accent)'}}>Open incident <ArrowRight size={15}/></Link></>:<p className="muted">No persisted unexplained loss currently meets the incident threshold.</p>}</div><div className="card" style={{padding:20}}><div className="kicker">Evidence health</div><div style={{display:'grid',gap:14,marginTop:18}}><Bar label="Meter coverage" value={data.meter_coverage}/><Bar label="Reading completeness" value={data.data_completeness}/><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span className="muted">Scenario</span><strong>{data.scenario}</strong></div><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span className="muted">Replay step</span><strong>{data.step}</strong></div></div></div></div>
    <div className="card" style={{padding:20,marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><div><div className="kicker">Recent evidence trail</div><h2 style={{fontSize:20,margin:'6px 0 0'}}>Latest domain events</h2></div><Link href="/audit" className="btn">Full audit trail</Link></div><div style={{display:'grid',gap:0}}>{data.recent_audit?.slice(0,8).map((a:any,i:number)=><div key={i} className="overview-audit-row" style={{display:'grid',gridTemplateColumns:'155px 190px 1fr',gap:14,padding:'10px 2px',borderTop:'1px solid var(--line)',fontSize:13}}><span className="muted">{new Date(a.timestamp).toLocaleString()}</span><strong>{a.event_type}</strong><span className="muted">{a.detail}</span></div>)}</div></div>
  </>}</div></AppShell>
}
function Metric({icon:Icon,label,value,danger}:{icon:any,label:string,value:string,danger?:boolean}){return <div className="card2" style={{padding:16}}><Icon size={18} color={danger?'var(--danger)':'var(--accent)'}/><div className="muted" style={{fontSize:12,marginTop:16}}>{label}</div><strong className="big-number" style={{fontSize:22,color:danger?'var(--danger)':'inherit'}}>{value}</strong></div>}
function Bar({label,value}:{label:string,value:number}){const p=Math.round((value||0)*100);return <div><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:7}}><span className="muted">{label}</span><strong>{p}%</strong></div><div style={{height:7,background:'#17231f',borderRadius:99,overflow:'hidden'}}><div style={{height:'100%',width:`${p}%`,background:'var(--accent)'}}/></div></div>}
