"use client";
import { useEffect,useState } from "react";
import { CheckCircle2, RefreshCw, XCircle } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { api } from "@/lib/api";

type Validation={passed:boolean;results:{name:string;passed:boolean;detail:string}[];note:string};
export default function ValidationPage(){const [data,setData]=useState<Validation|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);setError('');api<Validation>('/demo/validation').then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);return <AppShell><div className="page"><PageHeader title="Controlled validation" description="LeakLedger validates deterministic failure modes explicitly. These are controlled simulations, not claims of field detection accuracy." actions={<button className="btn" onClick={load}><RefreshCw size={15} style={{verticalAlign:'-2px',marginRight:6}}/>Re-run validation</button>}/>{error&&<div className="card error-banner">{error}</div>}{loading&&!data?<div className="muted">Running controlled scenarios…</div>:data&&<><div className="card" style={{padding:22,display:'flex',alignItems:'center',justifyContent:'space-between',gap:20,marginBottom:16}}><div><div className="kicker">Validation status</div><h2 style={{fontSize:28,margin:'8px 0 4px'}}>{data.passed?'All controlled scenarios passed':'A controlled scenario failed'}</h2><div className="muted">{data.note}</div></div>{data.passed?<CheckCircle2 size={38} color="var(--accent)"/>:<XCircle size={38} color="var(--danger)"/>}</div><div className="grid-2">{data.results.map(r=><div key={r.name} className="card" style={{padding:20}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}}><strong>{r.name}</strong>{r.passed?<span className="status status-RESOLVED">PASS</span>:<span className="status status-OPEN">FAIL</span>}</div><p className="muted" style={{fontSize:13,lineHeight:1.6,marginBottom:0}}>{r.detail}</p></div>)}</div></>}</div></AppShell>}
