"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Download, Upload } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { Status } from "@/components/Status";
import { API, api,fmt } from "@/lib/api";

type ImportResult={accepted:number;duplicates:number;rejected:{row:number;reason:string}[];total_rows:number};
export default function Meters(){
  const [rows,setRows]=useState<any[]>([]);const [error,setError]=useState('');const [result,setResult]=useState<ImportResult|null>(null);const [uploading,setUploading]=useState(false);const [loading,setLoading]=useState(true);const input=useRef<HTMLInputElement>(null);
  const load=()=>api<any[]>('/sites/northbridge/meters').then(r=>{setRows(r);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false));
  useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setError('');setResult(null);try{const data=new FormData();data.append('file',file);const r=await api<ImportResult>('/sites/northbridge/import',{method:'POST',body:data});setResult(r);load()}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setUploading(false);e.target.value=''}};
  return <AppShell><div className="page"><PageHeader title="Meter data" description="Current inventory and cumulative readings. CSV imports pass through the same backend validation and reconciliation contract as manual readings." actions={<><a className="btn" href={`${API}/sites/northbridge/import/sample`}><Download size={15} style={{verticalAlign:'-2px',marginRight:6}}/>Sample CSV</a><button className="btn btn-primary" onClick={()=>input.current?.click()} disabled={uploading}><Upload size={15} style={{verticalAlign:'-2px',marginRight:6}}/>{uploading?'Importing…':'Import CSV'}</button><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={upload}/></>}/>
    {error&&<div className="card error-banner">{error}</div>}{result&&<div className="card" style={{padding:16,marginBottom:16}}><strong>Import result</strong><span className="muted" style={{marginLeft:12}}>{result.accepted} accepted · {result.duplicates} duplicates · {result.rejected.length} rejected</span>{result.rejected.length>0&&<div style={{marginTop:10,fontSize:12}}>{result.rejected.slice(0,8).map(x=><div key={`${x.row}-${x.reason}`} style={{color:'var(--warn)'}}>Row {x.row}: {x.reason}</div>)}</div>}</div>}
    <div className="card table-wrap">{loading?<div className="empty-state">Loading meter inventory…</div>:<table className="table"><thead><tr><th>Meter</th><th>Parent</th><th>Type</th><th>Health</th><th>Latest cumulative</th><th>Latest timestamp</th><th>Expected interval</th><th>Readings</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.label}</strong><div className="muted" style={{fontSize:11}}>{r.id}</div></td><td>{r.parent_id||'—'}</td><td>{r.kind}{r.buffered?' · BUFFERED':''}</td><td><Status value={r.health}/></td><td>{r.latest_reading?`${fmt(r.latest_reading.cumulative_m3,3)} m³`:'—'}</td><td>{r.latest_reading?new Date(r.latest_reading.timestamp).toLocaleString():'—'}</td><td>{r.expected_interval_minutes} min</td><td>{r.reading_count}</td></tr>)}</tbody></table>}{!loading&&rows.length===0&&!error&&<div className="empty-state">No meter inventory is available.</div>}</div>
    <div className="card" style={{padding:18,marginTop:16}}><div className="kicker">CSV contract</div><code style={{display:'block',marginTop:10,color:'var(--accent)'}}>timestamp,meter_id,cumulative_m3</code><p className="muted" style={{fontSize:13,marginBottom:0}}>An optional <code>event_id</code> column is accepted. Invalid timestamps, unknown meters and malformed values are rejected with per-row reasons. Duplicate event IDs never double-count water.</p></div>
  </div></AppShell>
}
